### ISSUE TITLE
Rechercher par denominationUniteLegale, avec * et espaces

### ISSUE THREAD

**Issue by julienbdx** [SimonDevelop/sirene#1]
Bonjour,

Et merci pour cette API.

La connexion fonctionne et les recherches simples également. Je bloque par contre pour rechercher par denominationUniteLegale en introduisant des caractères joker (*) pour une recherche contenant des espaces.

Par exemple, je voudrais pouvoir retrouver "compagnie des petites secousses" en recherchant "*petites secousses*".
https://www.societe.com/societe/la-compagnie-des-petites-secousses-529602476.html

`$sirene->searchEtablissement(["company" => "*petites secousses*"])`
retourne
`Erreur de syntaxe dans le paramètre q=denominationUniteLegale:*petites secousses*`

`$sirene->searchEtablissement(["company" => "petites secousses"])`
retourne
`Erreur de syntaxe dans le paramètre q=denominationUniteLegale:petites secousses`

Pourriez-vous m'aider ?

Merci

**Comment by SimonDevelop** [comment]
Bonjour,

Je vais regarder ça, mais il me semble que je n'ai pas prévu de type de cas, je vais y remédier dans une future version patch ;)

Merci à vous

**Comment by SimonDevelop** [comment]
La release [1.1.1](https://github.com/SimonDevelop/sirene/releases/tag/1.1.1) répond à votre besoin, inutile d'ajouter le joker `*` l'appelle de la fonction comme ceci : `$sirene->searchEtablissement(["company" => "petites secousses"])` suffit.

Si vous souhaitez utiliser la release 1.1.0, vous pouvez utiliser le caractère `+` comme indicateur d'espace comme ceci : `$sirene->searchEtablissement(["company" => "petites+secousses"])`

**Comment by julienbdx** [comment]
Merci, impeccable :)
