### ISSUE TITLE
Ajout d'une méthode sur l'état du service

### ISSUE THREAD

**Issue by chou666** [SimonDevelop/sirene#3]
Besoin : 

Est il possible d'ajouter une méthode sur l'état du service

https://api.insee.fr/entreprises/sirene/V3/informations

Je peux faire une PR si besoin

**Comment by SimonDevelop** [comment]
Bonjour,

Je viens d'ajouter la fonction sur la [release 1.1.2](https://github.com/SimonDevelop/sirene/releases/tag/1.1.2).

Cordialement, Simon
