### ISSUE TITLE
searchEtablissement ne renvoie pas tous les résultats

### ISSUE THREAD

**Issue by vlmsl** [SimonDevelop/sirene#5]
Bonjour Simon,

En utilisant la fonction ainsi : 
`searchEtablissement(['siren' => '000000000']); // Siren remplacé par des 0 pour l'exemple`
La fonction ne renvoie pas tous les résultats attendus. 

Il semble que c'est la valeur par défaut de $page qui pose problème. En mettant 0, j'obtiens tous les résultats.

Pour obtenir les résultats attendus, j'ai changé
`public function searchEtablissement(array $params, string $tri = "siren", int $page = 1, int $nombre = 20)`
par
`public function searchEtablissement(array $params, string $tri = "siren", int $page = 0, int $nombre = 20)`

La documentation SIRENE précise pour le paramètre `debut` :

> Rang du premier élément demandé dans la réponse, défaut 0

Vincent

**Comment by SimonDevelop** [comment]
Il y a une page 0 pour la base siren ?

**Comment by vlmsl** [comment]
Surtout, la documentation de l'api SIRENE précise que le paramètre &debut est égal à 0 par défaut et quand on interroge directement leur API, oui, il y a une différence si on met &debut=0 ou &debut=1 (ça agit comme un offset).

**Comment by SimonDevelop** [comment]
Je vais corriger ça dans la soirée, merci pour l'info, j'ai peu regardé cette partie.
