### ISSUE TITLE
Warning: Undefined array key "access_token"

### ISSUE THREAD

**Issue by bastien70** [SimonDevelop/sirene#7]
Bonjour !

J'essaie d'utiliser ton bundle, j'ai suivi les indications, mais quand je tente une fonction, j'ai l'erreur "Warning: Undefined array key "access_token""

J'ai juste fait ceci : 

```php
$sirene = new Sirene([
            "secret" => base64_encode(sprintf('%s:%s', $this->sirenConsommateurKey, $this->sirenConsommateurSecret)),
            "jwt_path" => __DIR__ // Chemin où sera stocké le token d'accès (fichier json)
        ]);
```

Quand je dump le contenu de $sirene, j'ai ceci : 

![image](https://github.com/SimonDevelop/sirene/assets/53140475/bf62b91d-0ae5-4aeb-a458-b30bcb83312a)

A mon avis, mon soucis vient du jwt_path, mais je comprends pas ce que je suis censé faire ? Je dois créer un fichier et mettre quelque chose dedans ? Ou c'est automatique ?

**Comment by SimonDevelop** [comment]
Pourrais-tu me fournir la ligne ou apparaît comme cette erreur ?
Il s'agit sans doute du fichier `Sirene.php` (sauf si c'est une erreur de ton code)

Le fichier json se créer tout seul si tu donnes bien les permissions d'écriture, ce fichier sert à la librairie pour effectuer les appelles api avec les diverses fonctions, il ne faut pas y toucher soi-même.

**Comment by bastien70** [comment]
Oui voilà : 

![image](https://github.com/SimonDevelop/sirene/assets/53140475/99aa9cfa-8af1-46b5-a6a7-7b7dfc3a4ecd)

Je précise, le fichier ne semble pas se créer
Et oui j'utilise bien la bonne API Sirene, tout pareil

EDIT: Ok, en débuguant un peu, j'arrive à obtenir l'origine de l'erreur : `"{"error_description":"A valid OAuth client could not be found for client_id:Myqm282FsCV3efpEbg32Zxyp","error":"invalid_client"}"`

**Comment by SimonDevelop** [comment]
Ton `client_id` n'est donc pas bon, revérifie le sur le site de l'insee, probablement un caractère non copié/collé.

**Comment by bastien70** [comment]
Rhaaa je me déteeeste

Dans mon services.yaml, j'avais une parenthèse de trop sur la définition de mes paramètres...

```yaml
            $sirenConsommateurKey: '%env(SIRENE_CONSOMMATEUR_KEY)%)'
            $sirenConsommateurSecret: '%env(SIRENE_CONSOMMATEUR_SECRET)%)'
```

QUi doit en fait être 

```yaml
            $sirenConsommateurKey: '%env(SIRENE_CONSOMMATEUR_KEY)%'
            $sirenConsommateurSecret: '%env(SIRENE_CONSOMMATEUR_SECRET)%'
```

Bon bah effectivement ça marche mieux ! Désolé pour le dérangement, erreur d'étourderie..
