### ISSUE TITLE
Current API version is deprecated

### ISSUE THREAD

**Issue by bastien70** [SimonDevelop/sirene#9]
Hello, current api version is deprecated. Is it possible to use the new one ? Currently, we have now "errors 500"

![image](https://github.com/SimonDevelop/sirene/assets/53140475/ea14dc8d-f6dc-4fcc-b925-07f7752ac4b4)

EDIT : PR => https://github.com/SimonDevelop/sirene/pull/10

**Comment by SimonDevelop** [comment]
It's delivered!
